services:
    postgres:
        volumes:
            - ./data:/var/lib/artgallery/postgresql/data
        image: postgres:latest
        container_name: my_postgres_db
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: my_database
            POSTGRES_USER: my_user
            POSTGRES_PASSWORD: my_password

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
