services:
    postgres:
        container_name: artgallery-test-postgres
        volumes:
            - ./data:/var/lib/artgallery-test/postgresql/data
        image: postgres:latest
        restart: unless-stopped
        ports:
            - "5435:5432"
        environment:
            POSTGRES_DB: test
            POSTGRES_USER: test
            POSTGRES_PASSWORD: 1234
    redis:
      container_name: "artgallery-test-redis"
      image: "redis"
      ports:
          - "6379:6379"
