# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: "my_password"
          POSTGRES_USERNAME: "my_user"
          POSTGRES_DATABASE: "test_database"
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.100

    - name: Restore dependencies
      working-directory: "./ArtGallery"
      run: dotnet restore
  
    - name: Build
      working-directory: "./ArtGallery"
      run: dotnet build --no-restore

    - name: Restore Integration Tests
      working-directory: "./ArtGallery.Integration.Tests"
      run: dotnet restore

    - name: Run Integration Tests
      working-directory: "./ArtGallery.Integration.Tests"
      run: dotnet test
